language: java
script: mvn test
#  - jdk_switcher use openjdk8
#  jdk_switcher: command not found
#  The command "jdk_switcher use openjdk8" exited with 127.
#
dist: xenial
install: mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
jdk: openjdk8
  # Expected feature release number in range of 9 to 12, but got: 8
  # - oraclejdk8
  # - oraclejdk9
notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - mvn clean test cobertura:cobertura coveralls:report
